### ISSUE TITLE
lhafile.lhafile.BadLhafile: this file level is out of support range 32

### ISSUE THREAD

**Issue by sebastianbergmann** [bebbo/amigaos-cross-toolchain#36]
With current `master` (3cf47074e6d35474b49da01693b7bbf683646aa9) I run into:
```
INFO: preparing files for "ira"
DEBUG: enter directory ".build-m68k/tmp/tmpBLuWoK"
INFO: extract files from ".build-m68k/archives/ira.lha"
Traceback (most recent call last):
  File "./toolchain-m68k", line 902, in <module>
    globals()[action].__call__(*args.args)
  File "./toolchain-m68k", line 300, in build
    _build(True)
  File "./toolchain-m68k", line 608, in _build
    unpack('ira', top_dir='.', work_dir='{build}')
  File "/root/amigaos-cross-toolchain/common.py", line 38, in wrapper
    return fn(*args, **kwargs)
  File "/root/amigaos-cross-toolchain/common.py", line 359, in wrapper
    fn(*args, **kwargs)
  File "/root/amigaos-cross-toolchain/common.py", line 421, in unpack
    unarc(src)
  File "/root/amigaos-cross-toolchain/common.py", line 38, in wrapper
    return fn(*args, **kwargs)
  File "/root/amigaos-cross-toolchain/common.py", line 273, in unarc
    arc = lhafile.LhaFile(name)
  File "/root/amigaos-cross-toolchain/.build-m68k/host/lib/python2.7/site-packages/lhafile/lhafile.py", line 172, in __init__
    self._GetContents(callback=callback,args=args)
  File "/root/amigaos-cross-toolchain/.build-m68k/host/lib/python2.7/site-packages/lhafile/lhafile.py", line 181, in _GetContents
    info = self._RealGetContent()
  File "/root/amigaos-cross-toolchain/.build-m68k/host/lib/python2.7/site-packages/lhafile/lhafile.py", line 209, in _RealGetContent
    raise BadLhafile("this file level is out of support range %d" % os_level)
lhafile.lhafile.BadLhafile: this file level is out of support range 32
```

**Comment by sebastianbergmann** [comment]
Looks like Aminet was down and thus the downloaded file was invalid. Closing this in favor of #11.
