### ISSUE TITLE
"insn does not satisfy its constraints" -O3

### ISSUE THREAD

**Issue by MBeijer** [bebbo/amigaos-cross-toolchain#62]
```
XModule.cpp
../src/milkyplay/XModule.cpp: In static member function ‘static void XModule::convertc4spd(mp_uint32, mp_sbyte*, mp_sbyte*)’:
../src/milkyplay/XModule.cpp:1409:1: error: insn does not satisfy its constraints:
 }
 ^
(insn 573 572 574 (parallel [
            (set (reg:SI 4 d4)
                (truncate:SI (lshiftrt:DI (mult:DI (sign_extend:DI (reg:SI 5 d5))
                            (const_int 715827883 [0x2aaaaaab]))
                        (const_int 32 [0x20]))))
            (clobber (reg:SI 0 d0))
        ]) ../src/milkyplay/XModule.cpp:1333 203 {const_smulsi3_highpart}
     (expr_list:REG_UNUSED (reg:SI 5 d5)
        (expr_list:REG_DEAD (reg:SI 5 d5)
            (nil))))
../src/milkyplay/XModule.cpp:1409:1: internal compiler error: in final_scan_insn, at final.c:2923
0xd7a031 _fatal_insn(char const*, rtx_def const*, char const*, int, char const*)
        /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/rtl-error.c:108
0xd7a091 _fatal_insn_not_found(rtx_def const*, char const*, int, char const*)
        /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/rtl-error.c:118
0xa992a4 final_scan_insn(rtx_insn*, _IO_FILE*, int, int, int*)
        /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:2923
0xa97684 final(rtx_insn*, _IO_FILE*, int)
        /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:2045
0xa9be68 rest_of_handle_final
        /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:4455
0xa9c066 execute
        /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:4530
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
milkyplay.make:535: recipe for target 'obj/m68k-amigaos/Release/milkyplay/XModule.o' failed
```

**Comment by MBeijer** [comment]
also, I'm getting errors and graphical glitches in MilkyTracker when compiled with -Os on the most recent versions of the toolchain (beyond the a.out -> hunk change). Users are reporting 8000 0005 and 8000 0004 errors, and they are seemingly random. Sometimes at startup, sometimes at loading files and sometimes while saving settings.

**Comment by bebbo** [comment]
uhm, fautomat is building MilkyTracker with many combinations optimization levels, cpus and *-float and is only merging the changes to the gcc-6-branch if there is no error.

So please let me know how to reproduce this bug.

**Comment by MBeijer** [comment]
It does? Strange, I haven't done any changes to the milkytracker source. I have cloned the toolchain in a fresh folder before building it. 

I have however not removed the whole /opt/m68k-amigaos folder as I've put libs and includes there and don't really want to start from scratch with that with every update.

**Comment by MBeijer** [comment]
I'll do a clean install of the prefix and see if it fixes it and add to my update script to clean out everything but my own files.

**Comment by MBeijer** [comment]
During clean install I stumbled upon this:
```
INFO: download "http://aminet.net/dev/mui/MCC_NList-0.121.lha" to ".build-m68k/archives/mcc_nlist-0.121.lha"
...
urllib2.HTTPError: HTTP Error 404: Not Found
```
<img width="706" alt="screen shot 2018-01-19 at 15 51 03" src="https://user-images.githubusercontent.com/8772229/35156265-9d9bf4a6-fd30-11e7-9cc0-385ef5ba06de.png">

**Comment by MBeijer** [comment]
http://aminet.net/dev/mui/MCC_NList-0.124.lha is the latest

**Comment by MBeijer** [comment]
```
INFO: stubs: "68040.o" -> "/opt/m68k-amigaos/m68k-amigaos/libnix/lib/libnix/libstubs.a"
DEBUG: execute "m68k-amigaos-gcc -Wall -Os -fomit-frame-pointer -noixemul -c -o 68040.o 68040.c"
Traceback (most recent call last):
  File "./toolchain-m68k", line 902, in <module>
    globals()[action].__call__(*args.args)
  File "./toolchain-m68k", line 803, in install_sdk
    process_sdk(pkg, name, files)
  File "/home/marlon/amigaos-cross-toolchain/common.py", line 38, in wrapper
    return fn(*args, **kwargs)
  File "/home/marlon/amigaos-cross-toolchain/common.py", line 359, in wrapper
    fn(*args, **kwargs)
  File "./toolchain-m68k", line 736, in process_sdk
    add_stubs(c_file)
  File "./toolchain-m68k", line 676, in add_stubs
    execute('m68k-amigaos-gcc', '-Wall', '-Os', '-fomit-frame-pointer', *cflags)
  File "/home/marlon/amigaos-cross-toolchain/common.py", line 38, in wrapper
    return fn(*args, **kwargs)
  File "/home/marlon/amigaos-cross-toolchain/common.py", line 217, in execute
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by MBeijer** [comment]
The toolchain now builds as it should after the last commits. Will try to compile MilkyTracker again and see if I get the same insn error.

**Comment by MBeijer** [comment]
Yup, still fails when running -O3.

This is the full line of CPPFLAGS:
`-m68040 -mhard-float -O3 -fomit-frame-pointer -fno-exceptions -s -noixemul -fno-rtti -fpermissive`

```
../src/milkyplay/XModule.cpp: In static member function ‘static void XModule::convertc4spd(mp_uint32, mp_sbyte*, mp_sbyte*)’:
../src/milkyplay/XModule.cpp:1409:1: error: insn does not satisfy its constraints:
 }
 ^
(insn 573 572 574 (parallel [
            (set (reg:SI 4 d4)
                (truncate:SI (lshiftrt:DI (mult:DI (sign_extend:DI (reg:SI 5 d5))
                            (const_int 715827883 [0x2aaaaaab]))
                        (const_int 32 [0x20]))))
            (clobber (reg:SI 0 d0))
        ]) ../src/milkyplay/XModule.cpp:1333 203 {const_smulsi3_highpart}
     (expr_list:REG_UNUSED (reg:SI 5 d5)
        (expr_list:REG_DEAD (reg:SI 5 d5)
            (nil))))
../src/milkyplay/XModule.cpp:1409:1: internal compiler error: in final_scan_insn, at final.c:2923
0xd7a031 _fatal_insn(char const*, rtx_def const*, char const*, int, char const*)
        /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/rtl-error.c:108
0xd7a091 _fatal_insn_not_found(rtx_def const*, char const*, int, char const*)
        /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/rtl-error.c:118
0xa992a4 final_scan_insn(rtx_insn*, _IO_FILE*, int, int, int*)
        /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:2923
0xa97684 final(rtx_insn*, _IO_FILE*, int)
        /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:2045
0xa9be68 rest_of_handle_final
        /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:4455
0xa9c066 execute
        /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:4530
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
milkyplay.make:535: recipe for target 'obj/m68k-amigaos/Release/milkyplay/XModule.o' failed
make[1]: *** [obj/m68k-amigaos/Release/milkyplay/XModule.o] Error 1
Makefile:32: recipe for target 'milkyplay' failed
make: *** [milkyplay] Error 2
```

**Comment by bebbo** [comment]
please test

**Comment by MBeijer** [comment]
It seems to compile fine now.

**Comment by MBeijer** [comment]
Something is still wrong though!
https://www.eevul.net/downloads/milkytracker.68k
Crashes instantly with #80000005 on launch. Will do some further testing and see what I come up with

**Comment by bebbo** [comment]
please test

**Comment by MBeijer** [comment]
Seems to work fine now! Thank you!

**Comment by MBeijer** [comment]
However, loading bigger files crashes the application. :/

**Comment by bebbo** [comment]
please provide such a file

**Comment by MBeijer** [comment]
Hmm, now it suddenly works. What the .... I will come back with better evidence. Not being able to recreate the bug makes it seem rather random. But for some reason there are graphical glitches on the UI buttons and such. That stays, and there were none of that in the pre-hunk toolchain

I get a bunch of these throughout the compile, could be related maybe?:
```
/tmp/ccaVmpmK.s: Assembler messages:
/tmp/ccaVmpmK.s:1335: Warning: Bignum too big for f format; truncated
/tmp/ccaVmpmK.s:1444: Warning: Bignum too big for f format; truncated
/tmp/ccaVmpmK.s:1454: Warning: Bignum too big for f format; truncated
/tmp/ccaVmpmK.s:1560: Warning: Bignum too big for f format; truncated
/tmp/ccaVmpmK.s:1640: Warning: Bignum too big for f format; truncated
/tmp/ccaVmpmK.s:2185: Warning: Bignum too big for f format; truncated
/tmp/ccaVmpmK.s:2195: Warning: Bignum too big for f format; truncated
```

**Comment by MBeijer** [comment]
So that doesn't mess anything up?

**Comment by bebbo** [comment]
The Amiga knows only 32 bit values, with 64 bit a negative number becomes e.g. 0xffffffffffff1234 instead of 0xffff1234. but the resulting value after truncation is again 0xffff1234.

**Comment by MBeijer** [comment]
Alright

**Comment by MBeijer** [comment]
I'll close this for now. Will open a new issue if this reoccurs.
